Bump kubernetes 1.18.5+vmware.1 (#74)
* Bumps kubernetes 1.18.5+vmware.1
* Updates golang to version go1.13.10
* Adds pause 3.2
  source: https://buildweb.eng.vmware.com/sb/35936531/#
* Upgrades to coredns 1.6.7
* Allow tar.gz images to be loaded in kubelet post-start
* Adding wait to kube-scheduler to await kube-apiserver
* Upgrade cni-plugins
* bbr script improvements

Co-authored-by: Todd Sedano <tsedano@pivotal.io>
Co-authored-by: Shimon Walner <swalner@pivotal.io>
Co-authored-by: PKS CI Bot <ci@localhost>
Co-authored-by: Larry Hamel <lhamel@pivotal.io>
Co-authored-by: caleb miles <cmiles@pivotal.io>
Co-authored-by: Bridget Arthur <barthur@pivotal.io>
Co-authored-by: CJ Oster <ocj@pivotal.io>
Co-authored-by: CJ Oster <ocj@vmware.com>

diff --git a/jobs/bbr-etcd/templates/pre-restore-lock.sh.erb b/jobs/bbr-etcd/templates/pre-restore-lock.sh.erb
--- a/jobs/bbr-etcd/templates/pre-restore-lock.sh.erb
+++ b/jobs/bbr-etcd/templates/pre-restore-lock.sh.erb
@@ -1,26 +1,51 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -exuo pipefail
 
-echo "Stopping etcd"
-/var/vcap/bosh/bin/monit stop etcd
+NAME="$(basename "${0}")"
+LOG_DIR=/var/vcap/sys/log/bbr-etcd
+# tee will preserve the output to a log file and echo back
+# bbr will capture the stderr and echo back to the user if necessary
+exec > >(tee -a "$LOG_DIR/$NAME.stdout.log" >&2) 2>&1
 
-TIMEOUT=60
+ensure_etcd_stopped() {
+  if timeout "$TIMEOUT" /bin/bash <<EOF
+#!/bin/bash
 
-if timeout "$TIMEOUT" /bin/bash <<EOF
-  #!/bin/bash
-
-  until /var/vcap/bosh/bin/monit summary | grep etcd | grep "not monitored" ; do
-    echo "waiting for etcd to stop..."
-    sleep 5
-  done
+until /var/vcap/bosh/bin/monit summary | grep etcd | grep "not monitored" ; do
+  echo "waiting for etcd to stop..."
+  monit summary | grep etcd
+  sleep 5
+done
 EOF
-then
-  echo "Etcd stopped"
-else
-  echo "Timed out stopping etcd after $TIMEOUT seconds"
-  exit 1
-fi
+  then
+    echo "Etcd stopped"
+    retval=0
+  else
+    echo "Timed out stopping etcd after $TIMEOUT seconds"
+    retval=1
+  fi
+}
 
-echo "Deleting old etcd data"
-rm -rf /var/vcap/store/etcd
+main() {
+  echo "Stopping etcd on $(date)"
+  /var/vcap/bosh/bin/monit stop etcd
+
+  TIMEOUT=60
+  retval=0
+
+  ensure_etcd_stopped
+
+  if [ "$retval" == "1" ]; then
+    # in case monit stops the process between the last loop and here, we need "|| true"
+    killall -9 etcd || true
+    TIMEOUT=300
+    ensure_etcd_stopped
+    if [ "$retval" == "1" ]; then
+      echo "Unable to kill etcd in time"
+      exit 1
+    fi
+  fi
+}
+
+main
