Add debugging output and retries to kubelet post start
Co-authored-by: Sam Mirza <smirza@pivotal.io>
Co-authored-by: Daniel Keeney <dkeeney@pivotal.io>

diff --git a/jobs/kubelet/templates/bin/ensure_kubelet_up_and_running.erb b/jobs/kubelet/templates/bin/ensure_kubelet_up_and_running.erb
--- a/jobs/kubelet/templates/bin/ensure_kubelet_up_and_running.erb
+++ b/jobs/kubelet/templates/bin/ensure_kubelet_up_and_running.erb
@@ -7,6 +7,17 @@ kubectl="/var/vcap/packages/kubernetes/bin/kubectl --kubeconfig=/var/vcap/jobs/k
 # Wait for kubelet to become Ready before we move on to the next node.
 # Scheduling might not be enabled at this time.
 # The node then will be Ready;SchedulingDisabled
-until ${kubectl} get nodes -o wide -L bosh.id | grep -e ' Ready' | grep "<%= spec.id %>$"; do
+word_count=0
+until false
+do
+  # timeout may fail, but we want retries instead of exiting the script
+  set +e
+  node_output=`timeout 15 ${kubectl} get nodes -o wide -L bosh.id`
+  set -e
+  date
+  echo -e "node output:\n$node_output"
+  word_count=`${kubectl} get nodes -o wide -L bosh.id | grep -e ' Ready' | grep "<%= spec.id %>$" | wc -l`
+  [ $word_count -eq 1 ] && break
+  echo "sleeping"
   sleep 2
 done
