Move network-unavailable fix to start script
* Add guard for never initially finding target node

[#171168034]

Co-authored-by: Daniel Keeney <dkeeney@pivotal.io>
Co-authored-by: Shimon Walner <swalner@pivotal.io>
Co-authored-by: Larry Hamel <lhamel@pivotal.io>

diff --git a/jobs/kubelet/templates/bin/kubelet_ctl.erb b/jobs/kubelet/templates/bin/kubelet_ctl.erb
--- a/jobs/kubelet/templates/bin/kubelet_ctl.erb
+++ b/jobs/kubelet/templates/bin/kubelet_ctl.erb
@@ -9,6 +9,8 @@ PIDFILE=$RUN_DIR/kubelet.pid
 LOG_DIR=/var/vcap/sys/log/kubelet
 DATA_DIR=/var/vcap/store/kubernetes
 
+kubectl="/var/vcap/packages/kubernetes/bin/kubectl --kubeconfig=/var/vcap/jobs/kubelet/config/kubeconfig"
+
 <% iaas = nil %>
 <% if_p('cloud-provider') do |cloud_provider| %>
   <% iaas = cloud_provider %>
@@ -168,6 +170,105 @@ get_group_pid() {
   ps -ho pgrp "$(pid)"
 }
 
+wait_for_docker() {
+  # this function uses the exit status of "docker info" to decide to loop, so errors are acceptable
+  set +e
+  echo "waiting for docker info to return successfully ..."
+
+  docker_info_exit_code="-1"
+  startup_duration=0
+
+  while [[ "$startup_duration" -lt 120 && "$docker_info_exit_code" != "0" ]]; do
+    # sleeping first, to allow docker time to start up
+    startup_duration=$(( startup_duration+5 ))
+    sleep 5
+
+    # this is run as sudo, and doesn't have "docker" in the PATH
+    # it also needs the host to be explicitly set so that it does not default to:
+    # unix:///var/run/docker.sock
+    /var/vcap/packages/docker/bin/docker --host unix:///var/vcap/sys/run/docker/docker.sock info
+    docker_info_exit_code="$?"
+
+    echo "Have waited $startup_duration seconds for docker to be started"
+  done
+
+  if [ "$docker_info_exit_code" != "0" ]
+  then
+    echo "Docker is not running, exiting so that monit will restart kubelet"
+    exit 1
+  fi
+
+  set -e
+}
+
+find_current_ready_worker() {
+  local worker_name=$1
+  # As long as "o pipefail" is not set, this will result in empty string instead of aborting the script
+  # if the node is not ready, which is the behavior we want
+  $kubectl get nodes -o wide -L bosh.id | grep "^$worker_name" | grep ' Ready' | awk '{print $1}'
+}
+
+remove_network_unavailable_taint() {
+  node_name=""
+  ready_node_name=""
+  taint_wait_duration=0
+  while [[ "$taint_wait_duration" -lt 120 && ("$ready_node_name" != "$node_name" || "$node_name" == "") ]]; do
+    # sleeping first, to allow the k8s cluster to detect the taint
+    taint_wait_duration=$(( taint_wait_duration+20 ))
+    sleep 20
+    node_name=$($kubectl get nodes -o wide -L bosh.id | grep "<%= spec.id %>$" | awk '{print $1}')
+    if [ "$node_name" != "" ]
+    then
+      echo "Checking for Ready worker '$node_name'"
+      ready_node_name=$(find_current_ready_worker $node_name)
+    else
+      echo "Did not find a node name at $(date), will retry"
+    fi
+  done
+
+  if [[ "$node_name" == "" ]]
+  then
+    echo "Was not able to find node with id <%= spec.id %>"
+  elif [[ "$ready_node_name" != "$node_name" ]]
+  then
+    echo "Could not find $node_name listed as Ready, not attempting to remove NetworkUnavailable taint"
+  else
+    echo "Found $node_name as Ready, checking for NetworkUnavailable taint"
+    taint_bool="$($kubectl get nodes ${node_name} -o jsonpath='{.status.conditions[?(@.type=="NetworkUnavailable")].status}')"
+    if [ "$taint_bool" ==  "True" ]
+    then
+      echo "Found NetworkUnavailable taint, attempting to remove it"
+      v="$(cat <<-EOF
+      {
+        "status":{
+          "conditions": [
+           {
+              "type": "NetworkUnavailable",
+              "status": "False",
+              "reason": "NetworkProvidedByFlannel",
+              "message": "Status manually modified by CFCR kubelet post-start"
+           }
+          ]
+        }
+      }
+EOF
+      )"
+
+      KUBE_TOKEN=$($kubectl  config view -o jsonpath='{.users[?(@.name == "kubelet")].user.token}')
+      /usr/bin/curl -sS --cacert /var/vcap/jobs/kubelet/config/apiserver-ca.pem \
+        -H "Authorization: Bearer ${KUBE_TOKEN}" \
+        -H "Accept: application/json" \
+        -H "Content-Type: application/strategic-merge-patch+json" \
+        -X PATCH \
+        -d "$v" \
+        https://master.cfcr.internal:8443/api/v1/nodes/${node_name}/status
+
+      echo "Finished patching network availability"
+    else
+      echo "Did not find a NetworkUnavailable taint"
+    fi
+  fi
+}
 
 case $1 in
 
@@ -177,12 +278,17 @@ case $1 in
     send_process_stdout_to_logfile
     send_process_stderr_to_logfile
 
+    wait_for_docker
+
     pid_guard "$PIDFILE" "Kubelet"
 
     echo $$ > $PIDFILE
 
     delete_stale_drained_node
+    # Starting this in the background since start_kubelet never returns
+    remove_network_unavailable_taint &
     start_kubelet
+
     ;;
 
   stop)
