wip restore nsenter for kubelet/cni

diff --git a/jobs/kubelet/templates/bin/kubelet_ctl.erb b/jobs/kubelet/templates/bin/kubelet_ctl.erb
--- a/jobs/kubelet/templates/bin/kubelet_ctl.erb
+++ b/jobs/kubelet/templates/bin/kubelet_ctl.erb
@@ -103,6 +103,22 @@ get_hostname_override() {
 }
 
 start_kubelet() {
+# Previous versions of this script contained a destructive symlinking of a packaged binary called
+# `nsenter` because the utiil-linux package did not contain that binary on some Ubuntu release years
+# ago that is no longer an issue. So now, we ship the version of `nsenter` as a binary and restore
+# the state of the system. This is required in an upgrade scenario. New installs will just have
+# the appropriate binary in the appropriate place already.
+#
+# TODO - Remove this stuff in 1.10
+#
+  f="/usr/bin/nsenter"
+  if [ -L "${f}" ] && [ "$(readlink -f "${f}")" == "/var/vcap/jobs/kubelet/packages/cni/bin/nsenter" ]; then
+    rm "${f}" && cp "/var/vcap/jobs/kubelent/packages/cni/bin/nsenter" "/usr/bin/" || {
+      >&2 printf "Error: Unable to replace symlink to old nsenter with actual binary.\n"
+      exit 1
+    }
+  fi
+# -- END 1.9 nsenter hack
   <%-
     include_config = false
     if !iaas.nil? and iaas != "vsphere"
