First modification Binaries

diff --git a/packages/containerd/packaging b/packages/containerd/packaging
--- a/packages/containerd/packaging
+++ b/packages/containerd/packaging
@@ -1,6 +1,61 @@
 #!/usr/bin/env bash
 
-set -e
+set -eu
 
-tar xzf containerd/containerd-1.0.0.linux-amd64.tar.gz
-cp -R bin "${BOSH_INSTALL_TARGET}"
+# Extract containerd package
+CONTAINERD_VERSION=1.4.3
+tar xzvf containerd/cri-containerd-cni-${CONTAINERD_VERSION}-linux-amd64.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting containerd ${CONTAINERD_VERSION}"
+  exit 1
+fi
+
+echo "Copying containerd ${CONTAINERD_VERSION} binaries..."
+
+mkdir -p ${BOSH_INSTALL_TARGET}/bin
+cp usr/local/bin/* ${BOSH_INSTALL_TARGET}/bin
+cp usr/local/sbin/* ${BOSH_INSTALL_TARGET}/bin
+chmod +x ${BOSH_INSTALL_TARGET}/bin/*
+
+# LYZ 我们应该决定需要使用哪些Binaries，是不是有些没必要进去。CNI肯定没必要，因为我们有单独的CNI packages
+# 目前有的bin包含, 我们也需要知道这些binaries分别做啥
+# containerd  containerd-shim  containerd-shim-runc-v1  containerd-shim-runc-v2  crictl  critest  ctr  runc
+
+
+# Open Source Licensing Information, used by the vmware OSM system
+# These license abbreviations are defined by the OSM system
+# See https://github.com/pivotal-cf/pks-bosh-lifecycle-home/tree/master/osl/osm-blob-manifests
+
+AUTOCONF_LICENSE=GPL2.0
+AUTOCONF_SOURCE_URL="http://ftp.gnu.org/gnu/autoconf/$AUTOCONF_PACKAGE-$AUTOCONF_VERSION.tar.gz"
+BRIDGE_UTILS_SOURCE_URL="https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/bridge-utils/1.5-15ubuntu1/bridge-utils_1.5.orig.tar.gz"
+BRIDGE_UTILS_LICENSE="GPL2.0"
+
+# source: https://github.com/docker/docker-ce/blob/v18.09.8/components/engine/LICENSE
+DOCKER_LICENSE="Apache2.0"
+DOCKER_SOURCE_URL="https://github.com/docker/docker-ce/archive/v18.09.8.zip"
+
+cat <<EOF > ${BOSH_INSTALL_TARGET}/osl-package.json
+{ "packages": [
+    {
+    "name": "$AUTOCONF_PACKAGE",
+    "version": "$AUTOCONF_VERSION",
+    "url": "$AUTOCONF_SOURCE_URL",
+    "license": "$AUTOCONF_LICENSE"
+    },
+    {
+    "name": "$BRIDGE_UTILS_PACKAGE",
+    "version": "$BRIDGE_UTILS_VERSION",
+    "url": "$BRIDGE_UTILS_SOURCE_URL",
+    "license": "$BRIDGE_UTILS_LICENSE"
+    },
+    {
+    "name": "$DOCKER_PACKAGE",
+    "version": "$DOCKER_VERSION",
+    "url": "$DOCKER_SOURCE_URL",
+    "license": "$DOCKER_LICENSE"
+    }
+]}
+EOF
+
+#https://github.com/containerd/containerd/releases/download/v1.4.3/cri-containerd-cni-1.4.3-linux-amd64.tar.gz
